module.exports = {
  siteUrl: "https://pliseperde.com",
  generateRobotsTxt: true,
  generateIndexSitemap: false,
  changefreq: "monthly",
  priority: 0.7,
  sitemapSize: 5000,
  exclude: ["/admin/*", "/api/*", "/404"],
  robotsTxtOptions: {
    transformRobotsTxt: function () {
      return [
        "# ============================================",
        "# pliseperde.com — Robots.txt",
        "# Üst düzey AI + arama motoru optimizasyonu",
        "# ============================================",
        "",
        "# --- AI Crawler İzinleri (GEO) ---",
        "",
        "User-agent: OAI-SearchBot",
        "Allow: /",
        "Allow: /llms.txt",
        "",
        "User-agent: ChatGPT-User",
        "Allow: /",
        "Allow: /llms.txt",
        "",
        "User-agent: GPTBot",
        "Allow: /",
        "Allow: /llms.txt",
        "",
        "User-agent: PerplexityBot",
        "Allow: /",
        "Allow: /llms.txt",
        "",
        "User-agent: Perplexity-User",
        "Allow: /",
        "Allow: /llms.txt",
        "",
        "User-agent: Claude-SearchBot",
        "Allow: /",
        "Allow: /llms.txt",
        "",
        "User-agent: Claude-User",
        "Allow: /",
        "Allow: /llms.txt",
        "",
        "User-agent: ClaudeBot",
        "Allow: /",
        "Allow: /llms.txt",
        "",
        "User-agent: Google-Extended",
        "Allow: /",
        "Allow: /llms.txt",
        "",
        "User-agent: CCBot",
        "Allow: /",
        "Allow: /llms.txt",
        "",
        "User-agent: anthropic-ai",
        "Allow: /",
        "Allow: /llms.txt",
        "",
        "User-agent: Bytespider",
        "Allow: /",
        "Allow: /llms.txt",
        "",
        "User-agent: Applebot-Extended",
        "Allow: /",
        "Allow: /llms.txt",
        "",
        "User-agent: cohere-ai",
        "Allow: /",
        "Allow: /llms.txt",
        "",
        "# --- Standart Arama Motorları ---",
        "",
        "User-agent: Googlebot",
        "Allow: /",
        "Crawl-delay: 0",
        "",
        "User-agent: Googlebot-Image",
        "Allow: /",
        "Allow: /images/",
        "",
        "User-agent: Googlebot-Video",
        "Allow: /",
        "Allow: /video/",
        "",
        "User-agent: Bingbot",
        "Allow: /",
        "Crawl-delay: 1",
        "",
        "User-agent: BingPreview",
        "Allow: /",
        "",
        "User-agent: YandexBot",
        "Allow: /",
        "Crawl-delay: 1",
        "",
        "User-agent: YandexImages",
        "Allow: /",
        "Allow: /images/",
        "",
        "User-agent: DuckDuckBot",
        "Allow: /",
        "",
        "User-agent: Slurp",
        "Allow: /",
        "",
        "User-agent: Baiduspider",
        "Allow: /",
        "Crawl-delay: 2",
        "",
        "User-agent: facebookexternalhit",
        "Allow: /",
        "",
        "User-agent: Twitterbot",
        "Allow: /",
        "",
        "User-agent: LinkedInBot",
        "Allow: /",
        "",
        "User-agent: Pinterestbot",
        "Allow: /",
        "",
        "# --- Sosyal Medya Önizleme ---",
        "",
        "User-agent: *",
        "Allow: /",
        "Disallow: /admin/",
        "Disallow: /api/",
        "Disallow: /404",
        "Disallow: /*.json$",
        "Disallow: /*.xml$",
        "",
        "# --- Crawl-delay (Global) ---",
        "Crawl-delay: 1",
        "",
        "# --- Sitemap Referansları ---",
        "Sitemap: https://pliseperde.com/sitemap.xml",
        "Sitemap: https://pliseperde.com/sitemap-pages.xml",
        "Sitemap: https://pliseperde.com/sitemap-models.xml",
        "Sitemap: https://pliseperde.com/sitemap-services.xml",
        "Sitemap: https://pliseperde.com/sitemap-regions.xml",
            "Sitemap: https://pliseperde.com/sitemap-comparisons.xml",
        "Sitemap: https://pliseperde.com/sitemap-legal.xml",
        "Sitemap: https://pliseperde.com/sitemap-images.xml",
        "Sitemap: https://pliseperde.com/sitemap-videos.xml",
        "",
        "# --- llms.txt Referansı ---",
        "# AI asistanlar için içerik haritası: https://pliseperde.com/llms.txt",
        "",
      ].join("\n");
    },
  },
};
